### ISSUE TITLE
make no recompile if change only in rt.h macro

### ISSUE THREAD

**Issue by ScandalousMan** [ScandalousMan/RT#11]
steps to reproduce :
_in incs/rt.h_
change in # define RECURSION 0 (line 35) [from 1 to 0]
run command '$ make'

expected : whole project to recompile
result: no action

**Comment by ScandalousMan** [comment]
New test:
removing one element from structure (t_state *state from t_param)
Removing all code linked to param->state
command 'make'
command './RT' => segmentation fault

command 'make run'
command './RT' => OK

make doesn't include changes from incs/rt.h in the scenario either

**Comment by Its-Alex** [comment]
Branch ?

**Comment by Its-Alex** [comment]
Because makefile does not watch header file, you need to recompile all project for this

**Comment by jbouille42** [comment]
depend:
	@makedepend -- -Y -O -DHACK $(INC) -- $(SRC) >& /dev/null

**Comment by Its-Alex** [comment]
Makedepend output:
```
./srcs/Input.class.o: ./incs/Input.class.hpp
```
But object are in ./objs/xxx.o
