### ISSUE TITLE
Scene modification via GUI

### ISSUE THREAD

**Issue by Its-Alex** [ScandalousMan/RT#27]
- [ ] Coordonnées
- [ ] Global object properties

**Comment by ScandalousMan** [comment]
in t_object structure, we have added the *t_effects effects* attribute:
```C
typedef struct	s_effects
{
	char				color;
	char				normal;
}				t_effects;
```
t_effects structure contains 2 chars, based on the following enum:
```C
typedef enum			e_color_effect
{
	RT_C_NONE,
	RT_C_CHESS,
	RT_C_SIERPINSKI,
	RT_C_CLOUD,
	RT_C_MARBLE,
	RT_C_WOOD
}						t_color_effect;

typedef enum			e_normal_effect
{
	RT_N_NONE,
	RT_N_SINUS
}						t_normal_effect;
```
In the GUI, we should be able to select for each object a color_effect and a normal_effect in a select input.

**Comment by ScandalousMan** [comment]
When selecting an object, we should have access to:
- index (float value between 1.0 and 20.0)
- reflection (float value between 0.0 and 1.0)
- transparency (float value between 0.0 and 1.0, with 1.0 - reflection > transparency)
- col (r, g & b input between 0 and 255)
- kd (float value between 0.0 and 1.0)
- ks (float value between 0.0 and 1.0)
- color_effect (select input, refer to comment above)
- normal_effect (select input, refer to comment above)
- rotation (float[VEC_SIZE = 3] input)
- translation (float[VEC_SIZE = 3] input)

**Comment by ScandalousMan** [comment]
Priority order :
rotation (float[VEC_SIZE = 3] input)
translation (float[VEC_SIZE = 3] input)

color_effect (select input, refer to comment above)
normal_effect (select input, refer to comment above)

col (r, g & b input between 0 and 255)

**Comment by Its-Alex** [comment]
All is done
