### ISSUE TITLE
Makefile : make.depend error 127 + make re error 2

### ISSUE THREAD

**Issue by ScandalousMan** [ScandalousMan/RT#40]
RT:
  + Compile program: RT
make[1]: *** [Make.depend] Error 127
make: *** [re] Error 2

Libs glew, sdl2, pkg-config and sdl2_image are installed (NOT sdl2_images : conflict with README ?)

**Comment by Its-Alex** [comment]
One package is missing from readme I will add it, you can `brew bundle` to install all deps
