### ISSUE TITLE
SDL_PixelFormat

### ISSUE THREAD

**Issue by jbouille42** [ScandalousMan/RT#7]
RGBA32 format is used
I change in ARGB8888

Can we change format ARGB8888 to RGB888 ?

**Comment by Its-Alex** [comment]
Depends if we want to use alpha, why change to ARGB ?

**Comment by jbouille42** [comment]
ARGB because we can remove SDL_MapRGBA (commit: sdl format)

**Comment by jbouille42** [comment]
I think we don't use alpha

**Comment by Its-Alex** [comment]
For the moment no, but maybe later need to ask to @ScandalousMan

**Comment by Its-Alex** [comment]
RGBA8888 not better ? No need to switch alpha to first byte
I think we can remove SDL_MapRGBA without change format I just use it to make code better

**Comment by ScandalousMan** [comment]
Alpha not used in our calculations, so it really matters if it makes things easier for you guys

**Comment by jbouille42** [comment]
We remove alpha -> earn 25% of surface memory
